DROP DATABASE IF EXISTS photos;
CREATE DATABASE photos;

DROP TABLE IF EXISTS photo_votes;
CREATE TABLE photo_votes(
  id SERIAL,
  photo_id INTEGER PRIMARY KEY,
  likes INTEGER DEFAULT 0,
  dislikes INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  email VARCHAR(50),
  password VARCHAR(100)
);