INSERT INTO votes (photo_id) VALUES (0);
INSERT INTO votes (photo_id) VALUES (1);
INSERT INTO votes (photo_id) VALUES (2);
INSERT INTO votes (photo_id) VALUES (3);
INSERT INTO votes (photo_id) VALUES (4);
INSERT INTO votes (photo_id) VALUES (5);
INSERT INTO votes (photo_id) VALUES (6);
INSERT INTO votes (photo_id) VALUES (7);
INSERT INTO votes (photo_id) VALUES (8);
INSERT INTO votes (photo_id) VALUES (9);
INSERT INTO votes (photo_id) VALUES (10);
INSERT INTO votes (photo_id) VALUES (11);
INSERT INTO votes (photo_id) VALUES (12);
INSERT INTO votes (photo_id) VALUES (13);
INSERT INTO votes (photo_id) VALUES (14);
INSERT INTO votes (photo_id) VALUES (15);
INSERT INTO votes (photo_id) VALUES (16);
INSERT INTO votes (photo_id) VALUES (17);
INSERT INTO votes (photo_id) VALUES (18);
INSERT INTO votes (photo_id) VALUES (19);
INSERT INTO votes (photo_id) VALUES (20);
INSERT INTO votes (photo_id) VALUES (21);
INSERT INTO votes (photo_id) VALUES (22);
INSERT INTO votes (photo_id) VALUES (23);
INSERT INTO votes (photo_id) VALUES (24);
INSERT INTO votes (photo_id) VALUES (25);
INSERT INTO votes (photo_id) VALUES (26);
INSERT INTO votes (photo_id) VALUES (27);
INSERT INTO votes (photo_id) VALUES (28);
INSERT INTO votes (photo_id) VALUES (29);
INSERT INTO votes (photo_id) VALUES (30);
INSERT INTO votes (photo_id) VALUES (31);
INSERT INTO votes (photo_id) VALUES (32);
INSERT INTO votes (photo_id) VALUES (33);
INSERT INTO votes (photo_id) VALUES (34);
INSERT INTO votes (photo_id) VALUES (35);
INSERT INTO votes (photo_id) VALUES (36);
INSERT INTO votes (photo_id) VALUES (37);
INSERT INTO votes (photo_id) VALUES (38);
INSERT INTO votes (photo_id) VALUES (39);
INSERT INTO votes (photo_id) VALUES (40);
INSERT INTO votes (photo_id) VALUES (41);
INSERT INTO votes (photo_id) VALUES (42);
INSERT INTO votes (photo_id) VALUES (43);
INSERT INTO votes (photo_id) VALUES (44);
INSERT INTO votes (photo_id) VALUES (45);
INSERT INTO votes (photo_id) VALUES (46);
INSERT INTO votes (photo_id) VALUES (47);
INSERT INTO votes (photo_id) VALUES (48);
INSERT INTO votes (photo_id) VALUES (49);


INSERT INTO users (email, password) VALUES ('danny@yahoo.com', 'berkeley9');
INSERT INTO users (email, password) VALUES ('emily@gmail.com', 'berkeley2');
INSERT INTO users (email, password) VALUES ('brianna@yahoo.com', 'berkeley6');